### ISSUE TITLE
Won't post on self hosted exceptionless

### ISSUE THREAD

**Issue by xtianv** [exceptionless/Exceptionless.Net#130]
Hi,

Please help.
I'm trying to use a self hosting exceptionless on my machine but it won't post any log or exception.
I already put ServerUrl and EnableSSL on my config.
I also tried to switch it to online and its working.
The only problem is when I'm self hosted.

Please check this from my IIS Express.
I'm not sure if this is supposed to be like this.

![exceptionless_iisexpress](https://cloud.githubusercontent.com/assets/23511519/20469372/302f91ba-afda-11e6-980c-e0e825ad9410.png)

Regards,
Christian

**Comment by niemyjski** [comment]
That's showing off web sockets connecting to the server.  I'm guessing this issue is not with your client but your self hosted server. Are you seeing any events on your self hosted dashboards? Have you tried looking at our troubleshooting tips: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting

I'm betting your elastic search instance isn't configured properly (needs to have dynamic scripting on in the `elasticsearch.yml` file.  I'm going to close this for now, but please feel free to comment on this issue if that doesn't fix it or you can also join our slack: https://slack.exceptionless.com/
