### ISSUE TITLE
ExceptionLess.AspnetCore for .net standard 2.0

### ISSUE THREAD

**Issue by bukharin** [exceptionless/Exceptionless.Net#170]
Hi,

Our application works at asp.net core, but running on .net framework (not all libraries available on .net standard yet). Package `ExceptionLess.Aspnetcore` supports only `.netcore20` instead of `.netstandard20` target and can't be used on .net framework. 

I could not find any package for .net standard 2.0.

**Comment by niemyjski** [comment]
Hello,

The reason the package targets .net core app is because the meta package / dependency for https://www.nuget.org/packages/Microsoft.Extensions.DiagnosticAdapter/  There really is no way for us to just be net standard currently. I however am committing and will deploy a version that also targets full framework

**Comment by niemyjski** [comment]
A 4.2 release is currently being deployed which resolves this issue :)
