### ISSUE TITLE
Certificate is not validated in NET45

### ISSUE THREAD

**Issue by zivillian** [exceptionless/Exceptionless.Net#192]
https://github.com/exceptionless/Exceptionless.Net/blob/0ee9d35dce01105891910fe9857f584a4c813469/src/Exceptionless/Submission/DefaultSubmissionClient.cs#L123-L127

We've relied on this behavior since our own internal cert is not trusted on all machines, but we still think it's wrong to open all NET45 applications to an MiM Attack. We found this while migrating to ASP.NET Core which is always validating the certificate.

I would suggest to add a validation handler to the configuration to allow a simple validation for all existing users without creating a custom `ISubmissionClient`.

**Comment by niemyjski** [comment]
The thing is we need to allow self signed certs for local hosting, but at the same time it would be good to reduce the possibility of MiM attacks even if p2 data isn't being sent. I'm not sure the best course, perhaps we just remove this code all together? @ejsmith

**Comment by ejsmith** [comment]
Are you saying you want a config option that lets you control the cert validation?

**Comment by niemyjski** [comment]
Yes, that is what I believe is what he's saying. Which we could have a func<bool> thing is every platform has a slightly different handler.

**Comment by zivillian** [comment]
After implementing [my own validation](https://gist.github.com/zivillian/5c31096b76a0a1dbaa910e91157740db), I think adding a callback to the configuration is not the best way.

Adding a Thumbprint property to the configuration and default implementation of a new `ICertificateValidator` would reduce the effort for self hosting users and provide a good and easy starting point for more complex scenarios which need to validate other properties of the certificate.
Additionaly this can even increase the security for non self hosting users, by pinning the certificate.

**Comment by niemyjski** [comment]
@ejsmith thoughts on this, it doesn't seem like that bad. My question is what happens when you renew your cert or you get a different cert from some place else? I don't know if we can expect our thumbprint to always be the same can we?

**Comment by zivillian** [comment]
@niemyjski No, each certificate has its own thumbprint so it should be part of some configuration file or similar.
@ejsmith An extension method sound good, the idea was to make migration for existing users as easy as possible, without skipping the validation alltogether.

**Comment by ejsmith** [comment]
@zivillian I guess we could make it part of the client configuration that gets downloaded from the server. Otherwise you would need to update all clients any time a cert expired and you wanted to update it.

I'm not 100% sure that we need this. Really the only thing we are trying to accomplish is that the data is encrypted on transport. I guess having the server certificate validated would mean that data would not get submitted to a server that did not have the correct SSL cert. I guess that is what you are trying to protect against? Someone hacking the DNS and having access to your raw Exceptionless events, correct?

**Comment by niemyjski** [comment]
I don't know how you'd even be able to do that, because you have to make a request over ssl to get the thumbprint...

**Comment by zivillian** [comment]
The advantage of using the thumbprint is, that you only need to update the client if you change the certificate - the expiration date does not matter.
if you are manually changing something in one environment, you would have to manually do that in all other environments. Since we are (hopefully) talking only about internal self hosting without a somehow valid certificate (internal CA, Let's Encrpyt, etc.), I guess the number of clients should be really small,

**Comment by ejsmith** [comment]
The clients would be small if it's a web (server) app. But if it's some sort of desktop (client) app then it could be a ton of them. Which is why I don't think this is something we can do as a default, but I don't see any reason why we can't offer it as an option. Would you be able to submit a pull request for these changes?
