### ISSUE TITLE
Got wrong MachineName when using Exceptionless client v4.4.0

### ISSUE THREAD

**Issue by witskeeper** [exceptionless/Exceptionless.Net#233]
Got wrong MachineName when using Exceptionless client v4.4.0 with ASP.NET Core 3.1.x

Exceptionless  v4.3.x works well.

**Comment by niemyjski** [comment]
What is the difference between process machine name and the environment machine name for you? Also, I'm wondering if we should be filling back to look it up from the process if the environment machine name is empty. Looks like Process.MachineName will return the computer name where the process is running on . https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.machinename?view=netcore-3.1 Makes me think we should be using the process instead of the actual machine name.

**Comment by witskeeper** [comment]
this bug came from v4.4.0  and you can see the  changes of code.
old version use `process.MachineName` when `#elif !PORTABLE && !NETSTANDARD1_2`

So , we can just use `Environment.MachineName` now. 

![DE422C88-80A7-4173-94B9-169D7000CCAD](https://user-images.githubusercontent.com/5594094/88610784-1dc27880-d0ba-11ea-9b04-301d0f051583.png)

**Comment by niemyjski** [comment]
Thanks for the PR!

**Comment by witskeeper** [comment]
when will the new version be released ？

**Comment by niemyjski** [comment]
We like to try and get a few changes out in each release, can you use a nightly build for now?

**Comment by yuefengkai** [comment]
If this issues is resolved, please notify me, thank you @niemyjski

**Comment by niemyjski** [comment]
this issue is resolved and merged in, you can find the nuget packages on our nightly ci feed: https://f.feedz.io/exceptionless/exceptionless/nuget/index.json

**Comment by niemyjski** [comment]
I'll also release a new version sometime today.

**Comment by niemyjski** [comment]
A new release is building right now: https://github.com/exceptionless/Exceptionless.Net/releases/tag/v4.4.1
