### ISSUE TITLE
DuplicateCheckerPlugin

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.Net#25]
This DuplicateCheckerPlugin is too strict, take this for example:

``new Exception("Exception)"``
vs
``new Exception("OtherException)"``
vs
``new Exception("Exception", new Exception("InnerException"));``

These should not be marked as a duplicate.

**Comment by niemyjski** [comment]
Would you mind doing a pull request for unit tests for this. If we are not taking the exception message into account we should be. We check to see if an exception has been duplicated all the way up the stack because exceptions that occur on mvc might be reported by two different handlers but the outer exception will have a slightly different stack trace.

**Comment by Phyxion** [comment]
The message doesn't seem to be taken into account, nor the InnerException.

**Comment by niemyjski** [comment]
I'm closing this as the new duplicate checker that we ( @srijken ) are working on will taken into account the full event hashcode for deduplication.
