### ISSUE TITLE
Using Exceptionless.NLog with Exceptionless.AspNetCore can not capture the HTTP context information

### ISSUE THREAD

**Issue by h82258652** [exceptionless/Exceptionless.Net#262]
I found if I set ```serverUrl``` or ```apiKey``` in ```NLog.config```, the Exceptionless can not capture the HTTP context information (such as HTTP method).

I clone the source code and found the problem.
![Snipaste_2021-11-01_16-42-46](https://user-images.githubusercontent.com/5144550/139645350-68ffccfb-cb1b-4a4c-92a8-6786ef731046.png)

If we set ```serverUrl``` or ```apiKey```, in line 27, it will create a new ```ExceptionlessClient```.

![Snipaste_2021-11-01_16-43-28](https://user-images.githubusercontent.com/5144550/139645421-d512885a-1cd9-49e5-a4e2-304651a21fe3.png)

In ```UseExceptionless``` method, if we do not pass the client, it will get from the services or use the default client. And then register some plugins about asp.net core to log the HTTP context information. **But in the first step, it creates a new client and we can't pass it to the second step.**

**Comment by niemyjski** [comment]
This is by design, if you want to share additional integrations, plugins and configuration, don't set the server url or api key in the NLog config. We did this so you could specify a lightweight performant client instance just for logging but not something we actively recommend for most instances. If you need any help configuring the client, please let us know.
