### ISSUE TITLE
Event when crash report is submitted successfully

### ISSUE THREAD

**Issue by mallapurbharat** [exceptionless/Exceptionless.Net#34]
Feature Request:
Whenever a crash/exception happens, the submission form pops up. 
When the user submits the report, after submitting it, he should get a messagebox where he sees that it was submitted successfully. For any reason, if the submission wasn’t successful, he should see that it wasn’t able to submit it successfully. Probably a callback on push crash report fail/success would be best.

Looks like this feature isn't there yet. Request you to add support for this feature.

**Comment by niemyjski** [comment]
This would be a nice to have. Currently it's show the dialog and try to process it in the background.

**Comment by niemyjski** [comment]
We added an event to the client called `SubmittedEvent` which is fired after the event is processed but before it's enqueued. I don't think we will be adding an event after it's successfully posted or failed because they are processed in the background on a timer in batch. I think this would make it \ hard to show which ones have been submitted and which ones failed. We will keep retrying them x times until it succeeds otherwise we will discard the event. You could always inject your own DefaultEventQueue which extends ours and do anything you'd like..

Do you have a use case that you'd still need this knowing the above? If so would you mind sharing it? Until then I'm going to close this issue but feel free to comment on it, and if theres a good use case we will open it back up.
