### ISSUE TITLE
Logging aggregates when throtling has kicked in

### ISSUE THREAD

**Issue by danlarson** [exceptionless/Exceptionless.Net#72]
After monthly throttling has kicked in, I would like to see the top n (n =10?) issues be captured in aggregate, at least for paid accounts. Instead of shutting off logging until the next reset, can we get something like the following:

You've hit the limit and are being throttled. Here are the top exceptions that might be causing this: 

NullRefException            Count 10000  
DivideByZeroException  Count  3400 

...in which you stop recording exception details, but when new NullRefExceptions come in you just increment the count without storing it? 

Would that be possible? Are you throttling because the customer (me) is paying for a limited number of storage, in which this would be possible? 

Also, email notifications when error counts increase over a given threshold would be nice. "We've detected 340 exceptions more per day in the last 24 hours." Or something like that, where the number is a 40% increase over the previous weekly day average. So if something is loaded and exceptionless starts to get spammed we know.

**Comment by niemyjski** [comment]
You get this view by looking at the most frequent exceptions view: https://be.exceptionless.io/type/error/frequent It would be good if we sent a notification for this..

We are working on better deduplicating in the respective branch to where it increments a counter. But if you are over your limit the clients will not submit anything because any request is a resource usage. Every plan is based on submitted events, so if you get 15000 events you can send us 15k of errors, logs etc. I'm trying to find an issue for this but we are working with @srijken on this. Feel free to drop your comments in our gitter channel or here.

We have a issue created here for improved notifications and we will be working on this in the future: https://github.com/exceptionless/Exceptionless/issues/177

**Comment by niemyjski** [comment]
References https://github.com/exceptionless/Exceptionless/issues/112

**Comment by niemyjski** [comment]
I'm going to close this issue as I feel these outstanding issues cover your feedback (we greatly appreciate it). If you have any questions or concerns or feel that this is a different issue please comment back and we'll reopen this.
