### ISSUE TITLE
Line breaks in Exception.Message is removed when submitting the exception

### ISSUE THREAD

**Issue by andersgenberg** [exceptionless/Exceptionless.Net#98]
When you submit an `Exception` all line breaks are removed from `Exception.Message`.
Exapmle: 
```
try { 
  throw new NotSupportedException("Test\r\nLine\r\nBreaks"); 
} catch (Exception ex) { 
  ex.ToExceptionless().Submit(); 
}
```

When intercepting the message with Fiddler this is what is sent:
```
...
"message": "Test Line Breaks", 
"type": "System.NotSupportedException", 
...
```
![exception less in debugger](https://cloud.githubusercontent.com/assets/19546404/15507731/0dd0d692-21cd-11e6-94f6-a131425189b9.PNG)

**Comment by niemyjski** [comment]
It's being removed when we break down an exception into a model: https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Extras/Extensions/ToErrorModelExtensions.cs#L132 

@ejsmith I did a blame and it's been like that for a long time (since you imported it). Do you have any why we would have done this?

**Comment by niemyjski** [comment]
Upon further looking into we feel that this is a bug and we'll change this behavior in the near feature, we'll need to also update email templates and the spa app to handle new line characters properly.

**Comment by niemyjski** [comment]
This was fixed in a branch and will be pushed shortly :).

https://github.com/exceptionless/Exceptionless.Net/pull/119
